Fix Bayesian optimization error
keras-team/keras-tuner pull request #655
Opened 2022-02-12 15:56 UTC by Jet132

# Problem

Unlike documented in the [SciPy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult) the `OptimizeResult.fun` property can also be a scalar (See https://github.com/fmfn/BayesianOptimization/issues/60 for an example). This can lead to the following error:
```
TypeError: 'float' object is not subscriptable
```

# Solution

Check if `result.fun` is a scalar. If it is, use the value as is else get the first element as usual.

2022-03-01 14:20 UTC, STRATZ-Ken commented
I am having this issue, would be nice to get it approved.

2022-03-05 21:51 UTC, sndoja commented
I have also encountered the same issue.

2022-03-05 22:01 UTC, ilias-ant commented
same here.

2022-03-06 07:42 UTC, haifeng-jin commented
@Jet132 Would you please sign the Google CLA, by clicking the "Details" button on the CI?

2022-03-06 08:19 UTC, haifeng-jin commented
@STRATZ-Ken @sndoja @ilias-ant In what situation would this error be triggered in KerasTuner, please?

2022-03-06 08:34 UTC, ilias-ant commented
@haifeng-jin i'll try to provide a minimum reproducible example by the end of the day. :)

2022-03-06 12:28 UTC, Jet132 commented
> @Jet132 Would you please sign the Google CLA, by clicking the "Details" button on the CI?

Signed the CLA 👍

2022-03-06 15:45 UTC, STRATZ-Ken commented
After doing a lot of reading, it claims that in Tensorflow V2 and higher Eager is turned on by default.  This didn't seem to be true for me.

I had to turn `tf.compat.v1.enable_eager_execution()` on in my code, and the error went away.

2022-03-06 16:40 UTC, ilias-ant commented
```python
import sys

import keras_tuner as kt
import tensorflow as tf

sys.version
# '3.8.10 (default, Nov 26 2021, 20:14:08) \n[GCC 9.3.0]'

tf.__version__
# '2.8.0'

kt.__version__
# '1.1.0'

fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()


def build_model(hp):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(
    hp.Choice('units', [8, 16, 32]), activation='relu'))
    model.add(tf.keras.layers.Dense(1, activation='relu'))
    model.compile(loss='mse')
    
    return model


tuner = kt.BayesianOptimization(
    build_model,
    objective='val_loss',
    max_trials=5
)

tuner.search(train_images, train_labels, epochs=5, validation_split=0.2)

best_model = tuner.get_best_models()[0]
```

yields:

```
Trial 2 Complete [00h 00m 06s]
val_loss: 9.990598678588867

Best val_loss So Far: 9.990598678588867
Total elapsed time: 00h 00m 15s
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [12], in <cell line: 22>()
     13     return model
     16 tuner = kt.BayesianOptimization(
     17     build_model,
     18     objective='val_loss',
     19     max_trials=5
     20 )
---> 22 tuner.search(train_images, train_labels, epochs=5, validation_split=0.2)
     24 best_model = tuner.get_best_models()[0]

File ~/.cache/pypoetry/virtualenvs/fashion-mnist-classification-XxVOCvF_-py3.8/lib/python3.8/site-packages/keras_tuner/engine/base_tuner.py:169, in BaseTuner.search(self, *fit_args, **fit_kwargs)
    167 self.on_search_begin()
    168 while True:
--> 169     trial = self.oracle.create_trial(self.tuner_id)
    170     if trial.status == trial_module.TrialStatus.STOPPED:
    171         # Oracle triggered exit.
    172         tf.get_logger().info("Oracle triggered exit")

File ~/.cache/pypoetry/virtualenvs/fashion-mnist-classification-XxVOCvF_-py3.8/lib/python3.8/site-packages/keras_tuner/engine/oracle.py:189, in Oracle.create_trial(self, tuner_id)
    187     values = None
    188 else:
--> 189     response = self.populate_space(trial_id)
    190     status = response["status"]
    191     values = response["values"] if "values" in response else None

File ~/.cache/pypoetry/virtualenvs/fashion-mnist-classification-XxVOCvF_-py3.8/lib/python3.8/site-packages/keras_tuner/tuners/bayesian.py:232, in BayesianOptimizationOracle.populate_space(self, trial_id)
    227 for x_try in x_seeds:
    228     # Sign of score is flipped when maximizing.
    229     result = scipy_optimize.minimize(
    230         _upper_confidence_bound, x0=x_try, bounds=bounds, method="L-BFGS-B"
    231     )
--> 232     if result.fun[0] < optimal_val:
    233         optimal_val = result.fun[0]
    234         optimal_x = result.x

TypeError: 'float' object is not subscriptable
```

2022-03-06 19:19 UTC, haifeng-jin requested changes
@Jet132 Would you please run `shell/format.sh` to format the code and push again.

Thanks.

2022-03-06 19:22 UTC, haifeng-jin commented
@ilias-ant Thank you for the snippet!
I ran the code in colab and it is running fine.
It may be hard to reproduce. We don't have to for this one then.

2022-03-08 19:10 UTC, merged